client_config_backend: settings
client_config:
  client_id: 995814591462-3f8lenu4v1lsspjp8u1685g4mi4fha4s.apps.googleusercontent.com
  client_secret: scwRVeO6PovzXVn4NGd-Oh8L

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.readonly
